//
//  MockListingDataSource.swift
//  TrademeTechnicalTestApp
//
//  Created by Ryan Campion on 04/08/2024.
//

import Foundation
import Combine

class MockListingDataSource: ListingDataSource {
    
    func fetchListings() -> AnyPublisher<[Listing], Error> {
        // Create and array of 20 mock listings
        let mockListings = [
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "iPhone 8plus Silver 64GB",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$450.00",
                    buyNowPrice: 550.00,
                    reserveState: 0,
                    localImage: "iphone",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "1992 Toyota Hilux Surf",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: true,
                    pictureHref: nil,
                    priceDisplay: "$3,980",
                    buyNowPrice: nil,
                    reserveState: 4,
                    localImage: "surf",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "Dahlia Labyrinth",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$305.00",
                    buyNowPrice: 400.00,
                    reserveState: 1,
                    localImage: "dahlia",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "AirPods with Wireless Charging Case - excellent condition and free shipping",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$191.00",
                    buyNowPrice: 250.00,
                    reserveState: 2,
                    localImage: "airpods",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "iPhone 8plus Silver 64GB",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$450.00",
                    buyNowPrice: 550.00,
                    reserveState: 0,
                    localImage: "iphone",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "1992 Toyota Hilux Surf",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: true,
                    pictureHref: nil,
                    priceDisplay: "$3,980",
                    buyNowPrice: nil,
                    reserveState: 4,
                    localImage: "surf",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "Dahlia Labyrinth",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$305.00",
                    buyNowPrice: 400.00,
                    reserveState: 1,
                    localImage: "dahlia",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "AirPods with Wireless Charging Case - excellent condition and free shipping",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$191.00",
                    buyNowPrice: 250.00,
                    reserveState: 2,
                    localImage: "airpods",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "iPhone 8plus Silver 64GB",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$450.00",
                    buyNowPrice: 550.00,
                    reserveState: 0,
                    localImage: "iphone",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "1992 Toyota Hilux Surf",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: true,
                    pictureHref: nil,
                    priceDisplay: "$3,980",
                    buyNowPrice: nil,
                    reserveState: 4,
                    localImage: "surf",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "Dahlia Labyrinth",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$305.00",
                    buyNowPrice: 400.00,
                    reserveState: 1,
                    localImage: "dahlia",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "AirPods with Wireless Charging Case - excellent condition and free shipping",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$191.00",
                    buyNowPrice: 250.00,
                    reserveState: 2,
                    localImage: "airpods",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "iPhone 8plus Silver 64GB",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$450.00",
                    buyNowPrice: 550.00,
                    reserveState: 0,
                    localImage: "iphone",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "1992 Toyota Hilux Surf",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: true,
                    pictureHref: nil,
                    priceDisplay: "$3,980",
                    buyNowPrice: nil,
                    reserveState: 4,
                    localImage: "surf",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "Dahlia Labyrinth",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$305.00",
                    buyNowPrice: 400.00,
                    reserveState: 1,
                    localImage: "dahlia",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "AirPods with Wireless Charging Case - excellent condition and free shipping",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$191.00",
                    buyNowPrice: 250.00,
                    reserveState: 2,
                    localImage: "airpods",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "iPhone 8plus Silver 64GB",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$450.00",
                    buyNowPrice: 550.00,
                    reserveState: 0,
                    localImage: "iphone",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "1992 Toyota Hilux Surf",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: true,
                    pictureHref: nil,
                    priceDisplay: "$3,980",
                    buyNowPrice: nil,
                    reserveState: 4,
                    localImage: "surf",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "Dahlia Labyrinth",
                    region: "Auckland",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$305.00",
                    buyNowPrice: 400.00,
                    reserveState: 1,
                    localImage: "dahlia",
                    useLocalImage: true),
            Listing(id: Int.random(in: Int.min...Int.max),
                    title: "AirPods with Wireless Charging Case - excellent condition and free shipping",
                    region: "Wellington",
                    photoUrls: [],
                    isClassified: false,
                    pictureHref: nil,
                    priceDisplay: "$191.00",
                    buyNowPrice: 250.00,
                    reserveState: 2,
                    localImage: "airpods",
                    useLocalImage: true),
        ]
        
        return Just(mockListings)
            .setFailureType(to: Error.self)
            .eraseToAnyPublisher()
    }
}
